import { strToU8, zipSync } from 'fflate'
import * as THREE from 'three'
import type { PlatePlacement, ResinPrinterProfile } from '../platePlanner'

export type ThreeMfMesh = {
  name: string
  positions: Float32Array
}

export type ResinSupportPreset = 'light' | 'medium' | 'heavy'

export type Plate3mfOptions = {
  resinPreparation?: {
    printer: ResinPrinterProfile
    supportPreset: ResinSupportPreset
  }
  generatedSupports?: ThreeMfMesh
  modelElevationMm?: number
}

export function exportPlate3mf(placements: PlatePlacement[], meshes: Map<string, ThreeMfMesh>, options?: Plate3mfOptions): Uint8Array {
  const requestIds = [...new Set(placements.map((placement) => placement.requestId))]
  const objectIds = new Map(requestIds.map((requestId, index) => [requestId, index + 1]))
  const supportObjectId = options?.generatedSupports ? requestIds.length + 1 : undefined
  const objects = requestIds.map((requestId) => {
    const mesh = meshes.get(requestId)
    if (!mesh) {
      const placement = placements.find((candidate) => candidate.requestId === requestId)
      throw new Error(`Missing original mesh for ${placement?.name ?? requestId}`)
    }
    return objectXml(objectIds.get(requestId)!, mesh)
  })
  if (options?.generatedSupports && supportObjectId) objects.push(objectXml(supportObjectId, options.generatedSupports))
  const items = placements.map((placement) => {
    const mesh = meshes.get(placement.requestId)
    if (!mesh) throw new Error(`Missing original mesh for ${placement.name}`)
    return `    <item objectid="${objectIds.get(placement.requestId)}" transform="${placementTransform(
      placement,
      mesh.positions,
      options?.modelElevationMm ?? 0,
    )}" />`
  })
  if (supportObjectId) items.push(`    <item objectid="${supportObjectId}" />`)
  const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <metadata name="Application">PrintHub</metadata>
  <resources>
${objects.join('\n')}
  </resources>
  <build>
${items.join('\n')}
  </build>
</model>`

  const files: Record<string, Uint8Array> = {
    '[Content_Types].xml': strToU8(contentTypesXml),
    '_rels/.rels': strToU8(relationshipsXml),
    '3D/3dmodel.model': strToU8(model),
  }
  if (options?.resinPreparation) {
    files['Metadata/Slic3r_PE.config'] = strToU8(prusaSlicerResinConfig(options.resinPreparation, options.generatedSupports !== undefined))
  }
  return zipSync(files, { level: 6, mtime: new Date(1980, 0, 1) })
}

function prusaSlicerResinConfig({ printer, supportPreset }: NonNullable<Plate3mfOptions['resinPreparation']>, supportsAreBaked: boolean) {
  const preset = resinSupportPresets[supportPreset]
  const settings: Record<string, string | number> = {
    bed_shape: `0x0,${formatNumber(printer.widthMm)}x0,${formatNumber(printer.widthMm)}x${formatNumber(printer.depthMm)},0x${formatNumber(printer.depthMm)}`,
    display_height: formatNumber(printer.depthMm),
    display_width: formatNumber(printer.widthMm),
    layer_height: '0.05',
    max_print_height: formatNumber(printer.heightMm),
    pad_enable: supportsAreBaked ? 0 : 1,
    printer_settings_id: `PrintHub ${singleLine(printer.name)}`,
    printer_technology: 'SLA',
    sla_print_settings_id: `PrintHub ${supportPreset} supports`,
    support_base_diameter: 3,
    support_base_height: 1,
    support_base_safety_distance: 1,
    support_buildplate_only: 0,
    support_critical_angle: 45,
    support_head_front_diameter: preset.headFrontDiameter,
    support_head_penetration: preset.headPenetration,
    support_head_width: 3,
    support_max_bridge_length: 10,
    support_max_bridges_on_pillar: 3,
    support_max_pillar_link_distance: 10,
    support_object_elevation: printer.heightAllowanceMm,
    support_pillar_connection_mode: 'zigzag',
    support_pillar_diameter: preset.pillarDiameter,
    support_pillar_widening_factor: 0,
    support_points_density_relative: 100,
    support_points_minimal_distance: 1,
    support_small_pillar_diameter_percent: '60%',
    support_tree_type: 'default',
    supports_enable: supportsAreBaked ? 0 : 1,
  }
  return `; generated by PrintHub

${Object.entries(settings)
  .map(([key, value]) => `; ${key} = ${value}`)
  .join('\n')}
`
}

const resinSupportPresets = {
  light: { headFrontDiameter: 0.5, headPenetration: 0.3, pillarDiameter: 1 },
  medium: { headFrontDiameter: 0.8, headPenetration: 0.4, pillarDiameter: 1.2 },
  heavy: { headFrontDiameter: 1, headPenetration: 0.6, pillarDiameter: 1.5 },
} satisfies Record<ResinSupportPreset, { headFrontDiameter: number; headPenetration: number; pillarDiameter: number }>

function singleLine(value: string) {
  return value
    .replace(/[\r\n;]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function objectXml(id: number, mesh: ThreeMfMesh) {
  const indexed = indexPositions(mesh.positions)
  const vertices = indexed.vertices.map(
    ([x, y, z]) => `          <vertex x="${formatNumber(x)}" y="${formatNumber(y)}" z="${formatNumber(z)}" />`,
  )
  const triangles = indexed.triangles.map(([v1, v2, v3]) => `          <triangle v1="${v1}" v2="${v2}" v3="${v3}" />`)
  return `    <object id="${id}" type="model" name="${escapeXml(mesh.name)}">
      <mesh>
        <vertices>
${vertices.join('\n')}
        </vertices>
        <triangles>
${triangles.join('\n')}
        </triangles>
      </mesh>
    </object>`
}

function indexPositions(positions: Float32Array) {
  if (positions.length === 0 || positions.length % 9 !== 0) throw new Error('Original mesh does not contain complete triangles')
  const vertices: [number, number, number][] = []
  const triangles: [number, number, number][] = []
  const indices = new Map<string, number>()
  for (let offset = 0; offset < positions.length; offset += 9) {
    const triangle: [number, number, number] = [0, 0, 0]
    for (let vertex = 0; vertex < 3; vertex++) {
      const index = offset + vertex * 3
      const point: [number, number, number] = [positions[index], positions[index + 1], positions[index + 2]]
      if (!point.every(Number.isFinite)) throw new Error('Original mesh contains invalid coordinates')
      const key = point.join('|')
      let vertexIndex = indices.get(key)
      if (vertexIndex === undefined) {
        vertexIndex = vertices.length
        vertices.push(point)
        indices.set(key, vertexIndex)
      }
      triangle[vertex] = vertexIndex
    }
    triangles.push(triangle)
  }
  return { vertices, triangles }
}

function placementTransform(placement: PlatePlacement, positions: Float32Array, elevationMm: number) {
  const orientation = new THREE.Quaternion(...(placement.orientationQuaternion ?? [0, 0, 0, 1]))
  const bounds = new THREE.Box3()
  const point = new THREE.Vector3()
  for (let index = 0; index < positions.length; index += 3) {
    point.set(positions[index], positions[index + 1], positions[index + 2]).applyQuaternion(orientation)
    bounds.expandByPoint(point)
  }
  const plateRotation = new THREE.Quaternion().setFromAxisAngle(
    new THREE.Vector3(0, 0, 1),
    THREE.MathUtils.degToRad(placement.rotationZDegrees),
  )
  const rotatedCenter = bounds.getCenter(new THREE.Vector3()).applyQuaternion(plateRotation)
  const position = new THREE.Vector3(placement.xMm - rotatedCenter.x, placement.yMm - rotatedCenter.y, -bounds.min.z + elevationMm)
  const rotation = plateRotation.multiply(orientation)
  const elements = new THREE.Matrix4().compose(position, rotation, new THREE.Vector3(1, 1, 1)).elements
  return [
    elements[0],
    elements[1],
    elements[2],
    elements[4],
    elements[5],
    elements[6],
    elements[8],
    elements[9],
    elements[10],
    elements[12],
    elements[13],
    elements[14],
  ]
    .map(formatNumber)
    .join(' ')
}

function formatNumber(value: number) {
  if (Math.abs(value) < 1e-9) return '0'
  return value.toFixed(9).replace(/\.?0+$/, '')
}

function escapeXml(value: string) {
  return value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll("'", '&apos;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
}

const contentTypesXml = `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
  <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml" />
</Types>`

const relationshipsXml = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel" />
</Relationships>`
